### ISSUE TITLE
Kaladesh returning empty array

### ISSUE THREAD

**Issue by dnorthrupva** [JAndritsch/mtgextractor#16]
Unsure how to find out which card it is that's failing, but it's returning an empty array and breaking the parse on each pull.

`

> =====================================                                                                                                                        
> Processing set 'Kaladesh'...                                                                                                                                 
> =====================================                                                                                                                        
> 1 / 274: Processed card 'Accomplished Automaton'                                                                                                             
> 2 / 274: Processed card 'Acrobatic Maneuver'                                                                                                                 
> 3 / 274: Processed card 'Aerial Responder'                                                                                                                   
> 4 / 274: Processed card 'Aether Hub'                                                                                                                         
> 5 / 274: Processed card 'Aether Meltdown'                                                                                                                    
> 6 / 274: Processed card 'Aether Theorist'                                                                                                                    
> rake aborted!                                                                                                                                                
> NoMethodError: undefined method `[]' for nil:NilClass                                                                                                        
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/card_extractor.rb:159:in `extract_types'                                           
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/card_extractor.rb:32:in `parse_page'                                               
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/card_extractor.rb:63:in `get_card_details'                                         
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/mtgextractor/rails/tasks/mtgextractor.rake:66:in `block in process_set'            
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/mtgextractor/rails/tasks/mtgextractor.rake:63:in `each'                            
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/mtgextractor/rails/tasks/mtgextractor.rake:63:in `each_with_index'                 
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/mtgextractor/rails/tasks/mtgextractor.rake:63:in `process_set'                     
> /usr/local/rvm/gems/ruby-2.3.0/bundler/gems/mtgextractor-1336f5da0d94/lib/mtgextractor/rails/tasks/mtgextractor.rake:29:in `block (2 levels) in <top (require
> d)>'           

`

Any insight?

**Comment by dnorthrupva** [comment]
I believe it's on this card - http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=417611

**Comment by JAndritsch** [comment]
Hi @dnorthrupva, I appreciate you trying to help us track down and fix bugs but this project is no longer maintained.
