### ISSUE TITLE
Handling of latin characters

### ISSUE THREAD

**Issue by kirka121** [JAndritsch/mtgextractor#17]
Heya, wonderful gem. using it as we speak. however it seems a bit out of date with the new cards, E.g. there are some cards that start with the latin Æ which should be scraped as AE.

i forked and fixed this with a simple gsub, and also brought the tests up to date.
but i think the better solution is to add the I18N gem and run the regex_name generator through that

thanks for the spectacular work again.
best regards

**Comment by adback03** [comment]
@kirka121 this project has been dead for quite a few years. If you are in need of a ruby gem to scrape MTG cards, I'd go here: https://github.com/MagicTheGathering/mtg-sdk-ruby

**Comment by JAndritsch** [comment]
Hey @kirka121, unfortunately @adback03 is correct. We haven't maintained this repo in quite some time and there aren't any plans to revive it.
